export const CHAPTERS = [
  {
    id: 'e2',
    title: 'Elective 2: Building Web Products',
    items: [
      { title: 'Syllabus', file: '/elective-2-building-web-products.htm' },
      { title: 'Week 1: C# Translation Bootcamp', file: '/elective-2/week-01-csharp-translation-bootcamp.htm' },
      { title: 'Week 2: Interfaces & DI Mental Model', file: '/elective-2/week-02-interfaces-and-di-mental-model.htm' },
      { title: 'Week 3: HTTP & The Web', file: '/elective-2/week-03-http-and-the-web.htm' },
      { title: 'Week 4: MVC Big Picture', file: '/elective-2/week-04-mvc-big-picture.htm' },
      { title: 'Week 5: Routing Deep-Dive', file: '/elective-2/week-05-routing-deep-dive.htm' },
      { title: 'Week 6: Controllers & Action Results', file: '/elective-2/week-06-controllers-and-action-results.htm' },
      { title: 'Week 7: Views & Layouts', file: '/elective-2/week-07-views-and-layouts.htm' },
      { title: 'Week 8: Model Binding & Validation', file: '/elective-2/week-08-model-binding-and-validation.htm' },
      { title: 'Week 9: EF Core Fundamentals', file: '/elective-2/week-09-ef-core-fundamentals.htm' },
      { title: 'Week 10: Relationships & Data Display', file: '/elective-2/week-10-relationships-and-data-display.htm' },
      { title: 'Week 11: Consuming APIs with HttpClient', file: '/elective-2/week-11-consuming-apis-with-httpclient.htm' },
      { title: 'Week 12: Mini-Capstone Checkpoint', file: '/elective-2/week-12-mini-capstone-checkpoint.htm' },
      { title: 'Week 13: Authentication & Authorization', file: '/elective-2/week-13-authentication-and-authorization.htm' },
      { title: 'Week 14: Security Fundamentals', file: '/elective-2/week-14-security-fundamentals.htm' },
      { title: 'Week 15: Capstone Sprint', file: '/elective-2/week-15-capstone-sprint.htm' },
      { title: 'Week 16: Capstone Final', file: '/elective-2/week-16-capstone-final-deploy-and-present.htm' },
      { title: 'Full Discussions', file: '/elective-2-discussions.htm' },
    ],
  },
  {
    id: 'e3',
    title: 'Elective 3: Production-Grade Products',
    items: [
      { title: 'Syllabus', file: '/elective-3-production-grade-products.htm' },
      { title: 'Week 1: Modern JavaScript Review', file: '/elective-3/week-01-modern-javascript-review.htm' },
      { title: 'Week 2: Async JavaScript Deep-Dive', file: '/elective-3/week-02-async-javascript-deep-dive.htm' },
      { title: 'Week 3: TypeScript Essentials', file: '/elective-3/week-03-typescript-essentials.htm' },
      { title: 'Week 4: Dev Tooling & Workflow', file: '/elective-3/week-04-dev-tooling-and-workflow.htm' },
      { title: 'Week 5: Component Thinking in Vanilla JS', file: '/elective-3/week-05-component-thinking-in-vanilla-js.htm' },
      { title: 'Week 6: React Fundamentals', file: '/elective-3/week-06-react-fundamentals.htm' },
      { title: 'Week 7: Effects & Data Fetching', file: '/elective-3/week-07-effects-and-data-fetching.htm' },
      { title: 'Week 8: React Router & SPA Concepts', file: '/elective-3/week-08-react-router-and-spa-concepts.htm' },
      { title: 'Week 9: API Design Philosophy', file: '/elective-3/week-09-api-design-philosophy.htm' },
      { title: 'Week 10: ASP.NET Core Web API', file: '/elective-3/week-10-aspnet-core-web-api.htm' },
      { title: 'Week 11: Frontend-Backend Integration', file: '/elective-3/week-11-frontend-backend-integration.htm' },
      { title: 'Week 12: API Versioning & Documentation', file: '/elective-3/week-12-api-versioning-and-documentation.htm' },
      { title: 'Week 13: Auth Deep-Dive', file: '/elective-3/week-13-auth-deep-dive.htm' },
      { title: 'Week 14: Testing', file: '/elective-3/week-14-testing.htm' },
      { title: 'Week 15: CI/CD & Deployment', file: '/elective-3/week-15-ci-cd-and-deployment.htm' },
      { title: 'Week 16: Capstone Final', file: '/elective-3/week-16-capstone-final.htm' },
      { title: 'Full Discussions', file: '/elective-3-discussions.htm' },
    ],
  },
  {
    id: 'appendix',
    title: 'Appendices',
    items: [
      { title: 'Teaching Script Format', file: '/teaching-script-format.htm' },
    ],
  },
]

export const ALL_ITEMS = CHAPTERS.flatMap((s) => s.items)
